name: Deploy Sphinx documentation to Pages
on:
  push:
    branches: [ main, docs ] # TODO: we will remove docs once the action is working
jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python_version: '3.13.0'
        documentation_path: ./graphdoc/docs
        requirements_path: ./graphdoc/requirements.txt